version: "3"

services:
  synus:
    image: "synus"
    build: "."
    hostname: "synus"
    container_name: "synus"
    restart: "unless-stopped"
    command: "npm start"
    environment:
      DISCORD_TOKEN: "${DISCORD_TOKEN}"
      OWNERS: "${OWNERS}"
      PREFIXES: "${PREFIXES:-bot,>}"
